-- Création de la table users avec la colonne role
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    status BOOLEAN NOT NULL DEFAULT true,
    role VARCHAR(50) NOT NULL DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- Insertion d'un compte admin avec mot de passe haché
-- Le hash ci-dessous correspond à "motdepasseadmin" généré avec bcrypt et 10 salt rounds
INSERT INTO users (email, password, role, nom, prenom)
VALUES (
    'admin@example.com',
    '$2b$10$i3PRLsVQ7TY9J1xguNjdXutP.2Dcv2k1aK.fF5KooJKMhttk2f3CO',
    'admin',
    'Admin',
    'User'
);

-- Création de la table role_request pour gérer les demandes de changement de rôle
CREATE TABLE IF NOT EXISTS role_request (
    id SERIAL PRIMARY KEY,
    id_user INTEGER NOT NULL,
    lname VARCHAR(50) NOT NULL,
    fname VARCHAR(50) NOT NULL,
    desired_role VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user
      FOREIGN KEY (id_user)
      REFERENCES users(id)
      ON DELETE CASCADE,
    CONSTRAINT status_valid CHECK (status IN ('pending', 'accepted', 'refused'))
);

-- Table des stations (Infos qui ne changent pas souvent)
CREATE TABLE IF NOT EXISTS stations (
    station_id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100),
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    alt DOUBLE PRECISION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table des mesures météo (Données temporelles)
CREATE TABLE weather_measurements (
    station_id VARCHAR(50),
    reference_time TIMESTAMP,
    -- Données Précipitations
    rr1 DOUBLE PRECISION, qrr1 DOUBLE PRECISION,
    drr1 DOUBLE PRECISION, qdrr1 DOUBLE PRECISION,
    hneigef DOUBLE PRECISION, qhneigef DOUBLE PRECISION,
    neigetot DOUBLE PRECISION, qneigetot DOUBLE PRECISION,
    -- Données Température
    t DOUBLE PRECISION, qt DOUBLE PRECISION,
    td DOUBLE PRECISION, qtd DOUBLE PRECISION,
    tn DOUBLE PRECISION, qtn DOUBLE PRECISION,
    htn DOUBLE PRECISION, qhtn DOUBLE PRECISION,
    tx DOUBLE PRECISION, qtx DOUBLE PRECISION,
    htx DOUBLE PRECISION, qhtx DOUBLE PRECISION,
    dg DOUBLE PRECISION, qdg DOUBLE PRECISION,
    t10 DOUBLE PRECISION, qt10 DOUBLE PRECISION,
    t20 DOUBLE PRECISION, qt20 DOUBLE PRECISION,
    t50 DOUBLE PRECISION, qt50 DOUBLE PRECISION,
    t100 DOUBLE PRECISION, qt100 DOUBLE PRECISION,
    tnsol DOUBLE PRECISION, qtnsol DOUBLE PRECISION,
    tn50 DOUBLE PRECISION, qtn50 DOUBLE PRECISION,
    tchaussee DOUBLE PRECISION, qtchaussee DOUBLE PRECISION,
    tw DOUBLE PRECISION, qtw DOUBLE PRECISION,
    -- Données Pression
    pstat DOUBLE PRECISION, qpstat DOUBLE PRECISION,
    pmer DOUBLE PRECISION, qpmer DOUBLE PRECISION,
    geop DOUBLE PRECISION, qgeop DOUBLE PRECISION,
    pmermin DOUBLE PRECISION, qpmermin DOUBLE PRECISION,
    -- Données Vent
    ff DOUBLE PRECISION, qff DOUBLE PRECISION,
    dd DOUBLE PRECISION, qdd DOUBLE PRECISION,
    fxi DOUBLE PRECISION, qfxi DOUBLE PRECISION,
    dxi DOUBLE PRECISION, qdxi DOUBLE PRECISION,
    hxi DOUBLE PRECISION, qhxi DOUBLE PRECISION,
    fxy DOUBLE PRECISION, qfxy DOUBLE PRECISION,
    dxy DOUBLE PRECISION, qdxy DOUBLE PRECISION,
    hxy DOUBLE PRECISION, qhxy DOUBLE PRECISION,
    ff2 DOUBLE PRECISION, qff2 DOUBLE PRECISION,
    dd2 DOUBLE PRECISION, qdd2 DOUBLE PRECISION,
    fxi2 DOUBLE PRECISION, qfxi2 DOUBLE PRECISION,
    dxi2 DOUBLE PRECISION, qdxi2 DOUBLE PRECISION,
    hxi2 DOUBLE PRECISION, qhxi2 DOUBLE PRECISION,
    fxi3s DOUBLE PRECISION, qfxi3s DOUBLE PRECISION,
    dxi3s DOUBLE PRECISION, qdxi3s DOUBLE PRECISION,
    hxi3s DOUBLE PRECISION, qhxi3s DOUBLE PRECISION,
    -- Données Humidité
    u DOUBLE PRECISION, qu DOUBLE PRECISION,
    un DOUBLE PRECISION, qun DOUBLE PRECISION,
    hun DOUBLE PRECISION, qhun DOUBLE PRECISION,
    ux DOUBLE PRECISION, qux DOUBLE PRECISION,
    hux DOUBLE PRECISION, qhux DOUBLE PRECISION,
    uabs DOUBLE PRECISION, quabs DOUBLE PRECISION,
    dhumi40 DOUBLE PRECISION, qdhumi40 DOUBLE PRECISION,
    dhumi80 DOUBLE PRECISION, qdhumi80 DOUBLE PRECISION,
    dhumec DOUBLE PRECISION, qdhumec DOUBLE PRECISION,
    -- Données Diverses (Insolation, Rayonnement, Visibilité)
    tsv DOUBLE PRECISION, qtsv DOUBLE PRECISION,
    enth DOUBLE PRECISION, qenth DOUBLE PRECISION,
    ins DOUBLE PRECISION, qins DOUBLE PRECISION,
    glo DOUBLE PRECISION, qglo DOUBLE PRECISION,
    dir DOUBLE PRECISION, qdir DOUBLE PRECISION,
    dif DOUBLE PRECISION, qdif DOUBLE PRECISION,
    glo2 DOUBLE PRECISION, qglo2 DOUBLE PRECISION,
    uv DOUBLE PRECISION, quv DOUBLE PRECISION,
    infrar DOUBLE PRECISION, qinfrar DOUBLE PRECISION,
    uv_indice DOUBLE PRECISION, quv_indice DOUBLE PRECISION,
    -- Données Nébulosité
    n DOUBLE PRECISION, qn DOUBLE PRECISION,
    nbas DOUBLE PRECISION, qnbas DOUBLE PRECISION,
    cl DOUBLE PRECISION, qcl DOUBLE PRECISION,
    cm DOUBLE PRECISION, qcm DOUBLE PRECISION,
    ch DOUBLE PRECISION, qch DOUBLE PRECISION,
    n1 DOUBLE PRECISION, qn1 DOUBLE PRECISION,
    c1 DOUBLE PRECISION, qc1 DOUBLE PRECISION,
    b1 DOUBLE PRECISION, qb1 DOUBLE PRECISION,
    n2 DOUBLE PRECISION, qn2 DOUBLE PRECISION,
    c2 DOUBLE PRECISION, qc2 DOUBLE PRECISION,
    b2 DOUBLE PRECISION, qb2 DOUBLE PRECISION,
    n3 DOUBLE PRECISION, qn3 DOUBLE PRECISION,
    b3 DOUBLE PRECISION, qb3 DOUBLE PRECISION,
    c3 DOUBLE PRECISION, qc3 DOUBLE PRECISION,
    n4 DOUBLE PRECISION, qn4 DOUBLE PRECISION,
    c4 DOUBLE PRECISION, qc4 DOUBLE PRECISION,
    b4 DOUBLE PRECISION, qb4 DOUBLE PRECISION,
    -- Temps présent/passé
    ww DOUBLE PRECISION, qww DOUBLE PRECISION,
    vv DOUBLE PRECISION, qvv DOUBLE PRECISION,
    dvv200 DOUBLE PRECISION, qdvv200 DOUBLE PRECISION,
    w1 DOUBLE PRECISION, qw1 DOUBLE PRECISION,
    w2 DOUBLE PRECISION, qw2 DOUBLE PRECISION,
    -- Sol et Mer
    sol DOUBLE PRECISION, qsol DOUBLE PRECISION,
    solng DOUBLE PRECISION, qsolng DOUBLE PRECISION,
    tsneige DOUBLE PRECISION, qtsneige DOUBLE PRECISION,
    tubeneige DOUBLE PRECISION, qtubeneige DOUBLE PRECISION,
    esneige DOUBLE PRECISION, qesneige DOUBLE PRECISION,
    hneigefi3 DOUBLE PRECISION, qhneigefi3 DOUBLE PRECISION,
    hneigefi1 DOUBLE PRECISION, qhneigefi1 DOUBLE PRECISION,
    tmer DOUBLE PRECISION, qtmer DOUBLE PRECISION,
    vvmer DOUBLE PRECISION, qvvmer DOUBLE PRECISION,
    etatmer DOUBLE PRECISION, qetatmer DOUBLE PRECISION,
    dirhoule DOUBLE PRECISION, qdirhoule DOUBLE PRECISION,
    tlagon DOUBLE PRECISION, qtlagon DOUBLE PRECISION,
    uv2 DOUBLE PRECISION, quv2 DOUBLE PRECISION,
    ins2 DOUBLE PRECISION, qins2 DOUBLE PRECISION,
    infrar2 DOUBLE PRECISION, qinfrar2 DOUBLE PRECISION,
    dir2 DOUBLE PRECISION, qdir2 DOUBLE PRECISION,
    dif2 DOUBLE PRECISION, qdif2 DOUBLE PRECISION,
    
    -- Méta
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_mesure_per_time UNIQUE (station_id, reference_time)
);
-- Index pour accélérer les recherches (Indispensable pour les courbes Grafana)
CREATE INDEX idx_weather_station_time ON weather_measurements (station_id, reference_time DESC);